---
## Default Logstash configuration from logstash-docker.
## from https://github.com/elastic/logstash-docker/blob/master/build/logstash/config/logstash-full.yml
#
http.host: "0.0.0.0"
xpack.monitoring.elasticsearch.url: [ "http://10.10.108.130:9200" ]

## X-Pack security credentials
#
xpack.monitoring.enabled: true
path.config: /usr/share/logstash/pipeline
